-- =========================================================
-- PD06: PYTHON-SQL PROJECT
-- TARGET DATASET EXPLORATION:
-- AN SQL AND PYTHON APPROACH
-- =========================================================


-- =========================================================
-- BASIC PROBLEMS
-- =========================================================


-- Basic Problem 1:
-- List all unique cities where customers are located.

SELECT DISTINCT customer_city
FROM customers;


-- ---------------------------------------------------------
-- Basic Problem 2:
-- Count the number of orders placed in 2017.

SELECT COUNT(*) AS total_orders_2017
FROM orders
WHERE order_purchase_timestamp >= '2017-01-01'
  AND order_purchase_timestamp < '2018-01-01';


-- ---------------------------------------------------------
-- Basic Problem 3:
-- Find the total sales per category.

SELECT
    p."product category" AS product_category,
    SUM(oi.price) AS total_sales
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY p."product category"
ORDER BY total_sales DESC;


-- ---------------------------------------------------------
-- Basic Problem 4:
-- Calculate the percentage of orders that were paid in installments.

SELECT
    ROUND(
        100.0 * COUNT(DISTINCT CASE
            WHEN payment_installments > 1 THEN order_id
        END)
        / COUNT(DISTINCT order_id),
        2
    ) AS percentage_orders_paid_in_installments
FROM payments;


-- ---------------------------------------------------------
-- Basic Problem 5:
-- Count the number of customers from each state.

SELECT
    customer_state,
    COUNT(*) AS customer_count
FROM customers
GROUP BY customer_state
ORDER BY customer_count DESC;



-- =========================================================
-- INTERMEDIATE PROBLEMS
-- =========================================================


-- Intermediate Problem 1:
-- Calculate the number of orders per month in 2018.

SELECT
    EXTRACT(MONTH FROM order_purchase_timestamp) AS month,
    COUNT(*) AS order_count
FROM orders
WHERE order_purchase_timestamp >= '2018-01-01'
  AND order_purchase_timestamp < '2019-01-01'
GROUP BY EXTRACT(MONTH FROM order_purchase_timestamp)
ORDER BY month;


-- ---------------------------------------------------------
-- Intermediate Problem 2:
-- Find the average number of products per order,
-- grouped by customer city.

WITH products_per_order AS (
    SELECT
        o.order_id,
        o.customer_id,
        COUNT(oi.order_item_id) AS product_count
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY o.order_id, o.customer_id
)

SELECT
    c.customer_city,
    AVG(ppo.product_count) AS average_products_per_order
FROM products_per_order ppo
JOIN customers c
    ON ppo.customer_id = c.customer_id
GROUP BY c.customer_city
ORDER BY average_products_per_order DESC;


-- ---------------------------------------------------------

-- Intermediate Problem 3:
-- Calculate the percentage of total revenue contributed
-- by each product category.

WITH category_revenue AS (
    SELECT
        p."product category" AS product_category,
        SUM(oi.price) AS revenue
    FROM order_items oi
    JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY p."product category"
)

SELECT
    product_category,
    revenue,
    ROUND(
        100.0 * revenue / SUM(revenue) OVER (),
        2
    ) AS revenue_percentage
FROM category_revenue
ORDER BY revenue DESC;


-- ---------------------------------------------------------
-- Intermediate Problem 4:
-- Identify the correlation between product price and the
-- number of times a product has been purchased.

WITH product_purchase_data AS (
    SELECT
        product_id,
        AVG(price) AS product_price,
        COUNT(*) AS times_purchased
    FROM order_items
    GROUP BY product_id
)

SELECT
    CORR(product_price, times_purchased) AS correlation
FROM product_purchase_data;


-- ---------------------------------------------------------
-- Intermediate Problem 5:
-- Calculate the total revenue generated by each seller,
-- and rank them by revenue.

WITH seller_revenue AS (
    SELECT
        seller_id,
        SUM(price) AS total_revenue
    FROM order_items
    GROUP BY seller_id
)

SELECT
    seller_id,
    total_revenue,
    RANK() OVER (
        ORDER BY total_revenue DESC
    ) AS revenue_rank
FROM seller_revenue
ORDER BY revenue_rank;



-- =========================================================
-- ADVANCED PROBLEMS
-- =========================================================


-- Advanced Problem 1:
-- Calculate the moving average of order values for each
-- customer over their order history.

WITH order_values AS (
    SELECT
        o.order_id,
        o.customer_id,
        o.order_purchase_timestamp,
        SUM(oi.price) AS order_value
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY
        o.order_id,
        o.customer_id,
        o.order_purchase_timestamp
)

SELECT
    order_id,
    customer_id,
    order_purchase_timestamp,
    order_value,
    AVG(order_value) OVER (
        PARTITION BY customer_id
        ORDER BY order_purchase_timestamp
        ROWS BETWEEN 1 PRECEDING AND CURRENT ROW
    ) AS moving_average
FROM order_values
ORDER BY customer_id, order_purchase_timestamp;


-- ---------------------------------------------------------
-- Advanced Problem 2:
-- Calculate the cumulative sales per month for each year.

WITH monthly_sales AS (
    SELECT
        EXTRACT(YEAR FROM o.order_purchase_timestamp) AS year,
        EXTRACT(MONTH FROM o.order_purchase_timestamp) AS month,
        SUM(oi.price) AS monthly_sales
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY
        EXTRACT(YEAR FROM o.order_purchase_timestamp),
        EXTRACT(MONTH FROM o.order_purchase_timestamp)
)

SELECT
    year,
    month,
    monthly_sales,
    SUM(monthly_sales) OVER (
        PARTITION BY year
        ORDER BY month
    ) AS cumulative_sales
FROM monthly_sales
ORDER BY year, month;


-- ---------------------------------------------------------
-- Advanced Problem 3:
-- Calculate the year-over-year growth rate of total sales.

WITH yearly_sales AS (
    SELECT
        EXTRACT(YEAR FROM o.order_purchase_timestamp) AS year,
        SUM(oi.price) AS total_sales
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY EXTRACT(YEAR FROM o.order_purchase_timestamp)
),

yearly_sales_with_previous AS (
    SELECT
        year,
        total_sales,
        LAG(total_sales) OVER (
            ORDER BY year
        ) AS previous_year_sales
    FROM yearly_sales
)

SELECT
    year,
    total_sales,
    previous_year_sales,
    ROUND(
        100.0 * (total_sales - previous_year_sales)
        / NULLIF(previous_year_sales, 0),
        2
    ) AS yoy_growth_rate
FROM yearly_sales_with_previous
ORDER BY year;


-- ---------------------------------------------------------
-- Advanced Problem 4:
-- Calculate the retention rate of customers, defined as the
-- percentage of customers who make another purchase within
-- 6 months of their first purchase.

WITH first_purchase AS (
    SELECT
        customer_id,
        MIN(order_purchase_timestamp) AS first_purchase_date
    FROM orders
    GROUP BY customer_id
),

retained_customers AS (
    SELECT DISTINCT
        fp.customer_id
    FROM first_purchase fp
    JOIN orders o
        ON fp.customer_id = o.customer_id
    WHERE o.order_purchase_timestamp > fp.first_purchase_date
      AND o.order_purchase_timestamp <=
          fp.first_purchase_date + INTERVAL '6 months'
)

SELECT
    ROUND(
        100.0 * COUNT(rc.customer_id)
        / COUNT(fp.customer_id),
        2
    ) AS retention_rate
FROM first_purchase fp
LEFT JOIN retained_customers rc
    ON fp.customer_id = rc.customer_id;


-- ---------------------------------------------------------
-- Advanced Problem 5:
-- Identify the top 3 customers who spent the most money
-- in each year.

WITH customer_yearly_spending AS (
    SELECT
        o.customer_id,
        EXTRACT(YEAR FROM o.order_purchase_timestamp) AS year,
        SUM(oi.price) AS total_spent
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY
        o.customer_id,
        EXTRACT(YEAR FROM o.order_purchase_timestamp)
),

ranked_customers AS (
    SELECT
        customer_id,
        year,
        total_spent,
        RANK() OVER (
            PARTITION BY year
            ORDER BY total_spent DESC
        ) AS spending_rank
    FROM customer_yearly_spending
)

SELECT
    year,
    customer_id,
    total_spent,
    spending_rank
FROM ranked_customers
WHERE spending_rank <= 3
ORDER BY year, spending_rank;